config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toys, only: %i[index show new create] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index update]
  resources :users, only: %i[show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :toy

  enum approval_status: { approved: 0, pending: 1, denied: 2 }
  enum delivery_option: { "Delivery": 0, "Pick Up": 1 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :delivery_option, presence: true

  def pending?
    approval_status == 'pending'
  end
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  validates :category, presence: true
  # validates :dates_available, presence: true
  validates :price, presence: true
  validates :availability, presence: true
  enum condition: { "Brand new": 0, "Damaged": 1, "Used": 2 }

  # Querying booking for availability
  def self.unavailable(today, seven_days_from_now)
    # results = ActiveRecord::Base.connection.execute("SELECT * FROM bookings WHERE (bookings.toy_id = 164)")
    self.joins(:bookings).where("(bookings.start_date < ? AND bookings.end_date > ?) OR (bookings.start_date < ? AND bookings.end_date > ?)", today, seven_days_from_now, seven_days_from_now, seven_days_from_now).all
  end

end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_many :toys, dependent: :destroy
  has_many :bookings_as_owner, through: :toys, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc) # as a renter
    @bookings_as_owner = current_user.bookings_as_owner.order(created_at: :desc)
  end

  def new
    @toy = Toy.find(params[:toy_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    #puts "*****************" + @booking.start_date
    #raise
    @booking.toy = Toy.find(params[:toy_id])
    @booking.user = current_user

    authorize @booking
    if @booking.save
      redirect_to bookings_path # we need to update this once we have the root for booking index
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      # render # where was the booking update form?
      render :index
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :delivery_option, :approval_status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index




    if params[:query].present?
      @toys = policy_scope(Toy)
      @available_toys = availability_window_checker
      #@available_toys = Toy.where("name ILIKE ?", "%#{params[:query]}%")
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @available_toys = Toy.where(sql_query, query: "%#{params[:query]}%")

    else
      @toys = policy_scope(Toy)
      @available_toys = availability_window_checker
    end


  end

  def show
    set_toy
    @user_id = @toy.user.id
    @users = User.where(id: @user_id)
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude
      }

    end
  end

  def new
    @toy = Toy.new
    authorize @toy
  end

  def create
    @toy = Toy.new(toy_params)


    @toy.user = current_user
    authorize @toy


    if @toy.save
      redirect_to toy_path(@toy)
    else
      render :new
    end
  end

  private

  def availability_window_checker
    # date format: 2021-11-18
    today = DateTime.now.to_date
    seven_days_from_now = (today + 7).to_date

    @available_toys = []
    @unavailable_toys = @toys.unavailable(today, seven_days_from_now)

    @toys.each do |toy|
      @unavailable_toys.each do |unavailable_toy|
        if toy == unavailable_toy
          @toy_to_not_show = toy
        end
      end
      @available_toys << toy if toy != @toy_to_not_show
    end
    @available_toys
  end


  def set_toy
    @toy = Toy.find(params[:id])
    authorize @toy
  end

  def toy_params
    params.require(:toy).permit(:name, :description, :condition, :category, :price, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    #@toy = Toy.find(params[:id])
    set_user

  end

  private
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_approval_buttons.html.erb
<div class="approval-buttons">
  <% if booking.pending? %>
    <%= simple_form_for booking do |f| %>
      <%= f.input :approval_status, as: :hidden, input_html: { value: 'approved'} %>
      <%= f.submit 'Accept', class: 'btn btn-success approval-btns' %>
    <% end %>
    <%= simple_form_for booking do |f| %>
      <%= f.input :approval_status, as: :hidden, input_html: { value: 'denied'} %>
      <%= f.submit 'Reject', class: 'btn btn-dark approval-btns' %>
    <% end %>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [@toy, @booking] do |f|%>
  <%= f.input :start_date, input_html: { class:'form-date' } %>
  <%= f.input :end_date, input_html: { class:'form-date'} %>
  <%= f.input :delivery_option, collection: Booking.delivery_options.keys %>
  <%= f.submit class: 'btn btn-ghost', value: 'Reserve now!' %>
<% end %>

app/views/bookings/index.html.erb
<div class="pt-5 container-fluid bookings-back">
  <div class="container align-items-center">
    <div class="title">
      <h1 class="text-center pb-2">Your Reservations</h1>
    </div>
    <% if @bookings.empty?  %>
      <h4 style="">You don't have any reservations! 🙁</h4>
      <br>
      <%= link_to "Reserve toy", toys_path, class:"toys-button pl-5 pr-5" %>
      <br>
      <br>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="product-info">
          <div class="card-product mt-2">
            <%= cl_image_tag booking.toy.photo.key, height: 600, width: 800, crop: :fill %>
            <div class="card-product-infos">
              <h2 style="line-height: 0.85"><%= link_to booking.toy.name, toy_path(booking.toy)%></h2>
              <p><%= booking.toy.user.email %></p>
              <% if booking.approval_status == "approved" %>
                <p class ="booking-status" style="color:#008000"><%= booking.approval_status %></p>
              <% elsif booking.approval_status == "pending" %>
                <p class ="booking-status" style="color:#FFA500"><%= booking.approval_status %></p>
              <% elsif booking.approval_status == "denied" %>
                <p class ="booking-status" style="color:#FF0000"><%= booking.approval_status %></p>
              <% end %>
            </div>
          </div>
        </div>
        <% if policy(booking).update? %>
          <%= render "approval_buttons", booking: booking %>
        <% end %>
      <% end %>
    <% end %>
    <!--BOOKINGS AS A OWNER -->
    <div class="title">
      <h1 class="m-3 text-center">Reservation requests for you</h1>
    </div>
    <% if @bookings_as_owner.empty?  %>
      <br>
      <br>
      <h4>No reservations yet!</h4>
      <br>
      <br>
    <% else %>
      <% @bookings_as_owner.each do |booking| %>
        <div class="card-product mt-2">
          <%= cl_image_tag booking.toy.photo.key, height: 600, width: 800, crop: :fill %>
          <div class="card-product-infos">
            <h2 style="line-height: 0.85"><%= link_to booking.toy.name, toy_path(booking.toy)%></h2>
            <p><%= booking.toy.user.email %></p>
            <% if booking.approval_status == "approved" %>
              <p class ="booking-status" style="color:#008000"><%= booking.approval_status %></p>
            <% elsif booking.approval_status == "pending" %>
              <p class ="booking-status" style="color:#FFA500"><%= booking.approval_status %></p>
            <% elsif booking.approval_status == "denied" %>
              <p class ="booking-status" style="color:#FF0000"><%= booking.approval_status %></p>
            <% end %>
          </div>
        </div>
        <% if policy(booking).update? %>
          <%= render "approval_buttons", booking: booking %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <%= link_to "Return to Toys", toys_path, class: "btn btn-ghost bg-color-white ml-3"  %>
  <br>
  <br>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid form-background p-0">
  <div class="form-img"></div>
  <div class="container">
    <h1>Reserve <%= @toy.name %></h1>
    <%= render 'bookings/form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidsMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <div>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-container d-flex">
  <%= image_tag "toys-banner.jpg", class:"banner-img" %>
  <div class="container d-flex flex-column justify-content-center align-items-start">
      <h1>Kids marketplace!</h1>
      <p class='banner-p'>The best place to rent and borrow your toys!</p>
      <div class="page-buttons">
        <%= link_to "See our toys!", :toys, class:"btn btn-ghost my-2" %>
        <%= link_to "Lend your toys!", new_toy_path, class:"btn btn-ghost" %>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand pikachu" do %>
    <%= image_tag "https://secure.img1-fg.wfcdn.com/im/77981853/resize-h755-w755%5Ecompr-r85/8470/84707680/Pokemon+Pikachu+Wall+Decal.jpg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item ml-1 mr-1 mb-2">
          <%= link_to "Home", '/', class: "nav-link navbar-button" %>
        </li>
        <li class="nav-item ml-1 mr-1 mb-2">
          <%= link_to "Toys!", toys_path, class: "nav-link navbar-button" %>
        </li>
        <li class="nav-item ml-1 mr-1 mb-2">
          <%= link_to "Your Bookings", bookings_path, class: "nav-link navbar-button" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/82207189?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", "#", class: "dropdown-item" %>
            <%# <%= link_to "Manage your toys", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item ml-1 mr-1 mb-2">
          <%= link_to "Home", '/', class: "nav-link navbar-button" %>
        </li>
        <li class="nav-item ml-1 mr-1 mb-2">
          <%= link_to "Toys!", toys_path, class: "nav-link navbar-button" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link navbar-button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/toys/_form.html.erb
<%= simple_form_for @toy, :html=> { class: 'create-form' } do |f| %>
  <%= f.input :name, placeholder: 'Teddy bear', input_html: { autocomplete: 'off', class: "round-form" } %>
  <%= f.input :description, as: :text, placeholder: 'This is a cute Teddy bear!', input_html: { class: "round-form" } %>
  <%= f.input :category, placeholder: 'Soft Toy', input_html: { class: "round-form" }%>
  <%= f.input :price, placeholder: '600', label: "Price per week", input_html: { class: "round-form" } %>
  <%= f.input :condition, collection: Toy.conditions.keys, input_html: { class: "round-form" } %>
  <%= f.input :photo, as: :file, label: "Image" %>
  <%= f.submit class: 'btn btn-ghost', value: "Rent out!" %>
<% end %>

app/views/toys/index.html.erb
<div class="wrapper" style="align-content: center">
  <div class="toy-grid-container">
    <header style="float: left; margin-bottom: 20px; width: 100%; border: 0px solid #000;">
      <h1 class="km-index-title">Kids Marketplace</h1>
      <h3><%= @available_toys.count %> items available around the world.</h3>
      <%= form_tag toys_path, method: :get do %>
        <div class="km-search-bar-container"style="">
          <%= text_field_tag :query,
          params[:query],
          class: "km-search-bar__bar km-font-main",
          placeholder: "Find a toy"
          %>
          <%= button_tag(type: "Search", class: "km-search-bar__button km-text-background") do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </header>
    <!-- Make a partial here -->
    <div class="toy-grid">
      <% @available_toys.each do |toy| %>
        <div class="toy-grid__item">
          <%= link_to toy_path(toy.id) do %>
            <div class="toy-grid__item-photo-container">
              <% if toy.photo.attached? %>
                <%= cl_image_tag toy.photo.key, crop: :fill, class: "photo-class" %>
              <% else %>
                <%= image_tag 'background.jpg', crop: :fill, class: "photo-class" %>
              <% end %>
            </div>
            <div class="toy-grid__item-text-container">
              <%= link_to toy.name, toy_path(toy.id), class: "toy-text--name km-text-dark km-font-main" %>
              <p class="toy-text--description km-text-dark km-font-main"><%= toy.description %></p>
              <p class="toy-text--price km-text-dark km-font-main">Rental: <strong class="km-text-price km-text-highlight"><span>¥<%= toy.price %></strong></span>/week</p>
              <span class="toy-text--category km-font-main km-text-background"><%= toy.category %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="fixed-bottom">
  <div class="go-booking">
    <h2 style="color: black">Wanna rent out?</h2>
    <div class="btn btn-primary"><%= link_to "Click here", new_toy_path %></div>
  </div>
</div>

app/views/toys/new.html.erb
<div class="container-fluid form-background p-0">
  <div class="form-img"></div>
  <div class="container">
    <h3>Rent out your Toy!</h3>
    <%= render 'toys/form' %>
  </div>
</div>

app/views/toys/show.html.erb
<div class="container-fluid bookings-back">
  <div class="responsive container d-flex flex-column justify-content-between">
    <% if @toy.photo.attached? %>
      <%= cl_image_tag @toy.photo.key, class:'photo-class mt-3'%>
    <% else %>
      <%= image_tag 'background2.jpg', class:'photo-class'%>
    <% end %>
    <div class="show-title">
      <div>
        <h1><%= @toy.name %></h1>
        <p style="color: white"><% @toy.user.address %></p>
      </div>
      <div>
        <% if false %>
          <p>Edit</p>
        <% end %>
        <p style="color: gold">★★★<%# @toy.rating %></p>
      </div>
    </div>
    <div class="border-bottom"></div>
    <div class="toy-details">
      <div class="detail">
        <h3>Description: </h3>
        <% if @toy.description != nil %>
          <p style="color: white"><%= @toy.description %></p>
        <% else %>
          <p style="color: white" >No description to show</p>
        <% end %>
      </div>
      <div class="detail">
        <h3>Category: </h3>
        <% if @toy.category != nil %>
          <p style="color: white"><%= @toy.category.capitalize %></p>
        <% else %>
          <p>N/A</p>
        <% end %>
      </div>
      <div class="detail">
        <h3>Condition: </h3>
        <% if @toy.condition != nil %>
          <p style="color: white"><%= @toy.condition.capitalize %></p>
        <% else %>
          <p>N/A</p>
        <% end %>
      </div>
      <div class="border-bottom"></div>
      <div class="detail">
        <h3>Owner: <%= link_to @toy.user.name.capitalize, user_path(@toy) %></h3>
      </div>
      <div class="detail">
        <h3>Location: </h3>
        <% if @toy.user.address != nil %>
          <p style="color: white"><%= @toy.user.address.capitalize %></p>
        <% else %>
          <p>N/A</p>
        <% end %>
      </div>
      <div class="detail">
        <h3>Child's age: </h3>
        <% if @toy.user.child_age != nil %>
          <p style="color: white"><%= @toy.user.child_age %> years old</p>
        <% else %>
          <p>N/A</p>
        <% end %>
      </div>
      <div id="map"
     style="width: 100%; height: 360px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class="bottom-spacer mt-5 mb-5">
      </div>
    </div>
  </div>
  <div class="fixed-bottom">
    <div class="go-booking">
      <h2 style="color: black">¥<%= @toy.price %><span style="font-size:18px">/ week</span></h2>
      <div class="btn btn-primary"><%= link_to 'Check Availability', new_toy_booking_path(@toy) %></div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="responsive container d-flex flex-column justify-content-between">
  <div class="profile-top">
      <%= image_tag "https://avatars.githubusercontent.com/u/82207189?v=4" %>
    <h1><%= @user.name.upcase %><h1>
    <p>Address: <%= @user.address %></p>
    <p>Kid's age: <%= @user.child_age %></p>



<div class="border-bottom"></div>
<h2>Toys</h2>
    <div class="toy-grid">
      <% @user.toys.each do |toy| %>
        <div class="toy-grid__item">
          <%= link_to toy_path(toy.id) do %>
            <div class="toy-grid__item-photo-container">
              <%= cl_image_tag toy.photo.key, crop: :fill, class: "photo-class" %>
            </div>
            <div class="toy-grid__item-text-container">
              <%= link_to toy.name, toy_path(toy.id), class: "toy-text--name km-text-dark km-font-main" %>
              <p class="toy-text--description km-text-dark km-font-main"><%= toy.description %></p>
              <p class="toy-text--price km-text-dark km-font-main">Rental: <strong class="km-text-price"><span>¥<%= toy.price %></strong></span>/week</p>
            </div>
          <% end %>
        </div>
<% end %>
</div>
</div>